// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABH4_a8fvRcLXV09lzvrg0mLW7-8HhT5k',
    appId: '1:163488846991:web:8ff4003662929b0df20cfa',
    messagingSenderId: '163488846991',
    projectId: 'shopio-bb520',
    authDomain: 'shopio-bb520.firebaseapp.com',
    storageBucket: 'shopio-bb520.firebasestorage.app',
    measurementId: 'G-Y3LR7K4CFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_u_VBEkmhoDAKIZmJywco5nOAtusUgsg',
    appId: '1:163488846991:android:8b752d7581820e9ef20cfa',
    messagingSenderId: '163488846991',
    projectId: 'shopio-bb520',
    storageBucket: 'shopio-bb520.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqT69TWe0YAJSkfvtlwS2LYlbfJVxHYsI',
    appId: '1:163488846991:ios:fd9a9aa2deced830f20cfa',
    messagingSenderId: '163488846991',
    projectId: 'shopio-bb520',
    storageBucket: 'shopio-bb520.firebasestorage.app',
    iosBundleId: 'com.example.shopio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqT69TWe0YAJSkfvtlwS2LYlbfJVxHYsI',
    appId: '1:163488846991:ios:fd9a9aa2deced830f20cfa',
    messagingSenderId: '163488846991',
    projectId: 'shopio-bb520',
    storageBucket: 'shopio-bb520.firebasestorage.app',
    iosBundleId: 'com.example.shopio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABH4_a8fvRcLXV09lzvrg0mLW7-8HhT5k',
    appId: '1:163488846991:web:aff1c3543c9ee44bf20cfa',
    messagingSenderId: '163488846991',
    projectId: 'shopio-bb520',
    authDomain: 'shopio-bb520.firebaseapp.com',
    storageBucket: 'shopio-bb520.firebasestorage.app',
    measurementId: 'G-PDSCZMLSX8',
  );

}